# Generated by Django 5.2.13 on 2026-05-07 17:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data_warehouse", "0050_alter_externaldataschema_latest_error"),
    ]

    operations = [
        migrations.AddField(
            model_name="externaldatajob",
            name="cdc_write_mode",
            field=models.CharField(
                blank=True,
                help_text="For CDC syncs, the write mode this job materialised: `incremental_merge` for the consolidated table or `scd2_append` for the cdc-only history table. Lets the Syncs UI distinguish the two ExternalDataJob rows produced when `cdc_table_mode='both'`.",
                max_length=64,
                null=True,
            ),
        ),
    ]
